### ISSUE TITLE
Promote to org

### ISSUE THREAD

**Issue by jnv** [superfaceai/superface-daily#1]
- [x] Migrate repo
- [x] Setup failure notification to Slack channel
- [ ] Trigger upon SDK/CLI release

**Comment by freaz** [comment]
For OneSDK added in https://github.com/superfaceai/one-sdk-js/commit/07f92e17b1f8220729be0f0490ed90b135084d9a
For CLI added in https://github.com/superfaceai/cli/commit/61de5b9751d729847e172f220b4d67f9ce4993f8
